### ISSUE TITLE
`InputQueue::default` sometimes panics on WASM

### ISSUE THREAD

**Issue by akhilles** [aevyrie/bevy_editor_cam#13]
This is the line that can panic: https://github.com/aevyrie/bevy_editor_cam/blob/10f39791ec7488534e5385433bfaec1daf5756c8/src/controller/smoothing.rs#L75.

AFAIK, there's no guarantee that the monotonic clock value is large enough to be able to subtract the intervals without underflow. Would it be reasonable to detect when this happens using [`checked_sub`](https://docs.rs/bevy/latest/bevy/utils/struct.Instant.html#method.checked_sub) and not push those entries onto the queue?

**Comment by aevyrie** [comment]
Fix released in 0.2.6
