### ISSUE TITLE
zoom_through_objects affects maximum zoom when zooming out

### ISSUE THREAD

**Issue by ghost** [aevyrie/bevy_editor_cam#20]
When setting `zoom_through_objects` to true, the `max_size_per_pixel` is ignored. This is because if zoom through objects is enabled the previously calculated `clamped_scaled_zoom` value is not used. 
https://github.com/aevyrie/bevy_editor_cam/blob/f0387799e12cce9662a4789e6f64225c4b0aa143/src/controller/component.rs#L420-L426

This should probably be reflected in the docs of `zoom_through_objects`, or there could be another option to enable or disable the zoom out limit, analogous to how `zoom_through_objects` affects the zoom-in limit.

**Comment by aevyrie** [comment]
`zoom_through_objects` is more like "clamp velocity at limits instead of halting", but that seems more opaque than the chosen name.

**Comment by m-edlund** [comment]
You're right that it would not make for a good name, but currently the doc comment of `zoom_through_objects` does not mention this at all. So it would probably be helpful to add another sentence such as: 

"Additionally, when reaching `max_size_per_pixel`, the camera does not continue zooming out, but instead continues at the same speed"

**Comment by aevyrie** [comment]
Sounds good. Currently working through a few tricky bugs that I found before releasing this change, I'll try to remember to improve the docs here. Thanks!
