### ISSUE TITLE
Loading blink + anchor bug

### ISSUE THREAD

**Issue by Vrixyz** [aevyrie/bevy_editor_cam#30]
When the example `pseudo_ortho`  loads, I can see a blink frame where the model is not visible, if I start orbiting at that time, I lose completely all models (I can't see them anymore whatsoever), and the anchor is rendering weirdly.

<details><summary>Video reproduction</summary>
<p>

[Screencast from 12-16-2024 10:35:58 AM.webm](https://github.com/user-attachments/assets/6c6270f1-2d5c-4bde-b60a-f4fdd95cb319)

![image](https://github.com/user-attachments/assets/1e2282f8-a09e-4edd-a410-1a0678a5f6fc)

</p>
</details> 

The camera seems catapulted far away, and scrolls is more sensitive, but I didn´t investigate more.

**Comment by aevyrie** [comment]
That example is a bit of a hack already. I'd like to just remove it. The problem I was trying to solve was that certain depth effects were not working in ortho, however, that is a different problem related to precision caused by the near/far planes.

**Comment by aevyrie** [comment]
Example removed as it was a big hack anyway.
